Inicio da implementação do CSS
Pendulun/SistemaMercado pull request #24
Opened 2022-06-24 19:31 UTC by ricardobrunoc

Implementação do CSS aplica em duas páginas, produtos e add produtos

2022-06-24 19:55 UTC, Pendulun requested changes
O base.html não deveria possuir a abertura das tags html e body.  Acredito que o melhor a se fazer é criar dois arquivos html: 

- [ ]  Um  que contém só as tags \<link\> para importar o CSS necessário. Esse arquivo seria usado como {{include \<nome-arquivo\>.html}} de dentro do head de cada página html original

- [ ]  Um que contém apenas o div do "menu" com o logo embaixo. Ele seria importado após a abertura da tag body de dentro de cada página html original como {{ include \<menu\>.html }}

Dessa forma, todo arquivo já existente mantém a estrutura contida nele de html, head e body, mas com dois includes dentro. As outras estilizações em títulos e tabelas seriam feitas dentro do html original, assim como já está feito.

2022-06-25 20:29 UTC, Pendulun requested changes
Agora, o base.html não deveria existir. Digo isso para que a abertura das tags html, head e body não fiquem em um arquivo (base.html) e fechem em outro (index e addProduct).

- [x] O addProduct.html e o index.html devem manter a sua estrutura completa de tags abrindo e fechando \<html\>, \<head\> e \<body\> neles mesmos, apenas incluindo o links.html e o menu.html.
- [ ] Não esqueça de fechar as tags \<body\> e \<html\> em addProduct e em index

2022-06-26 13:40 UTC, ricardobrunoc commented
Implementação do FontAwsome

2022-06-26 15:13 UTC, Pendulun approved these changes
Vi que o links.html está repetido por app mas vou aprovar.

2022-06-26 15:13 UTC, merged